# Generated by Django 4.2.1 on 2023-06-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pdf_text',
            field=models.TextField(blank=True),
        ),
    ]
