# Generated by Django 4.2.1 on 2023-06-02 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_audio_file_path_audio_audio_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audio',
            old_name='audio_path',
            new_name='audio',
        ),
    ]
